### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Fimo4ka** [cy33hc/vita-ftp-client#2]
Is it possible to translate it into Russian?

**Comment by cy33hc** [comment]
@Fimo4ka Will be adding other languages soon.

**Comment by cy33hc** [comment]
@Fimo4ka I've added support for multiple languages. Do you want to help out with doing the translations. Use following file as template https://github.com/cy33hc/vita-ftp-client/blob/main/lang/English.ini

**Comment by Fimo4ka** [comment]
Thanks. 

> @Fimo4ka Я добавил поддержку нескольких языков. Вы хотите помочь с переводами. Используйте следующий файл в качестве шаблона https://github.com/cy33hc/vita-ftp-client/blob/main/lang/English.ini

Thanks. I translated it into Russian.

**Comment by Fimo4ka** [comment]
https://drive.google.com/file/d/1cKJY0-ZZadpFZxVrPB87Ig6sVltbWaYf/view?usp=sharing

**Comment by cy33hc** [comment]
@Fimo4ka Thx for the translation. This has being implemented and released in v1.40. Just update the software and you should get the changes.
