### ISSUE TITLE
Can't open Remote Folders from another Vita

### ISSUE THREAD

**Issue by DRok17** [cy33hc/vita-ftp-client#4]
Using Vitashell's FTP option, while I'm able to connect just fine I'm not able to open any folders:

![image](https://user-images.githubusercontent.com/81541725/166122724-c47f13b1-2bf5-47c0-808a-b9cb205b1840.png)

Directory field just shows the directory repeated when selected.

**Comment by AndreDK7** [comment]
I had the same issue doing this with my psp go

**Comment by cy33hc** [comment]
@DRok17 @AndreDK7 Thx for reporting. I didn't test with VitaShell. I'll fix it.

**Comment by cy33hc** [comment]
@DRok17 @AndreDK7 Fixed in v1.14. Closing

**Comment by AndreDK7** [comment]
It's working perfect now with psp go. Probably with vitashell too.

**Comment by DRok17** [comment]
Working on Vitashell, thanks!
